[package]
name = "rsh-lsp"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pretty_env_logger = "0.4.0"
tokio = { version = "1.7.1", features = ["full"] }
tower-lsp = "0.14.1"
